GET http://localhost:3003/api/blogs
###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYwODg0YmQxY2ViMzE0NzNkNjcyZDFjYSIsImlhdCI6MTYxOTU5OTY2M30.A_6v81_BSl8RDk08e_6e6UGTTN323E8RO2SCsNwS_Zs

{
    "title": "This is a blog title",
    "author": "James Author",
    "url": "http://www.google.com",
    "likes": 666
}
###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "This is a blog title",
    "author": "James Author",
    "url": "http://www.google.com",
    "likes": 666
}
###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Blog title 2",
    "author": "Blogman McNamara",
    "url": "http://www.google.com",
    "likes": 777
}
###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Blog title 4",
    "author": "Barack Blogama",
    "url": "http://www.google.com",
    "likes": 15
}